language: elixir
elixir:
  - 1.4
otp_release:
  - 20.0
before_script:
  - mix deps.get
script:
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
notifications:
  email: false
